{
    "name": "Odoo School Hospital",
    "version": "19.0.1.0.1",
    "category": "Customizations",
    "summary": "Odoo School Hospital",
    "description": "Odoo School Hospital",
    "website": "https://www.odoo.school",
    "author": "Odoo SA",
    "license": "OPL-1",
    "depends": [
        "base",
    ],
    "external_dependencies": {"python": []},
    "data": [
        'security/ir.model.access.csv',
        'views/odoo_school_library_menu.xml',
        'views/odoo_school_library_doctor_views.xml',
        'views/odoo_school_library_patient_views.xml',
        'views/odoo_school_library_disease_views.xml',
        'views/odoo_school_library_visit_views.xml',
    ],
    'demo': [
    'demo/odoo_school_library_doctor.xml',
    'demo/odoo_school_library_patient.xml',
    'demo/odoo_school_library.disease.csv',
    'demo/odoo_school_library.visit.csv',
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
    "images": ["static/description/icon.png"],
}
